// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/wa_template_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/wa_template_repository.go -destination=internal/repository/mocks/mock_wa_template_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "ppi-100-sis/internal/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockWATemplateRepository is a mock of WATemplateRepository interface.
type MockWATemplateRepository struct {
	ctrl     *gomock.Controller
	recorder *MockWATemplateRepositoryMockRecorder
	isgomock struct{}
}

// MockWATemplateRepositoryMockRecorder is the mock recorder for MockWATemplateRepository.
type MockWATemplateRepositoryMockRecorder struct {
	mock *MockWATemplateRepository
}

// NewMockWATemplateRepository creates a new mock instance.
func NewMockWATemplateRepository(ctrl *gomock.Controller) *MockWATemplateRepository {
	mock := &MockWATemplateRepository{ctrl: ctrl}
	mock.recorder = &MockWATemplateRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWATemplateRepository) EXPECT() *MockWATemplateRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockWATemplateRepository) Create(template *domain.WATemplate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", template)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockWATemplateRepositoryMockRecorder) Create(template any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockWATemplateRepository)(nil).Create), template)
}

// Delete mocks base method.
func (m *MockWATemplateRepository) Delete(id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockWATemplateRepositoryMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockWATemplateRepository)(nil).Delete), id)
}

// GetAll mocks base method.
func (m *MockWATemplateRepository) GetAll() ([]domain.WATemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].([]domain.WATemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockWATemplateRepositoryMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockWATemplateRepository)(nil).GetAll))
}

// GetByID mocks base method.
func (m *MockWATemplateRepository) GetByID(id uint) (*domain.WATemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*domain.WATemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockWATemplateRepositoryMockRecorder) GetByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockWATemplateRepository)(nil).GetByID), id)
}

// Update mocks base method.
func (m *MockWATemplateRepository) Update(id uint, name, bodyTemplate string, isDefault bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", id, name, bodyTemplate, isDefault)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockWATemplateRepositoryMockRecorder) Update(id, name, bodyTemplate, isDefault any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockWATemplateRepository)(nil).Update), id, name, bodyTemplate, isDefault)
}
