// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/infaq_type_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/infaq_type_repository.go -destination=internal/repository/mocks/mock_infaq_type_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "ppi-100-sis/internal/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockInfaqTypeRepository is a mock of InfaqTypeRepository interface.
type MockInfaqTypeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockInfaqTypeRepositoryMockRecorder
	isgomock struct{}
}

// MockInfaqTypeRepositoryMockRecorder is the mock recorder for MockInfaqTypeRepository.
type MockInfaqTypeRepositoryMockRecorder struct {
	mock *MockInfaqTypeRepository
}

// NewMockInfaqTypeRepository creates a new mock instance.
func NewMockInfaqTypeRepository(ctrl *gomock.Controller) *MockInfaqTypeRepository {
	mock := &MockInfaqTypeRepository{ctrl: ctrl}
	mock.recorder = &MockInfaqTypeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInfaqTypeRepository) EXPECT() *MockInfaqTypeRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockInfaqTypeRepository) Create(infaqType *domain.InfaqType) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", infaqType)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockInfaqTypeRepositoryMockRecorder) Create(infaqType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockInfaqTypeRepository)(nil).Create), infaqType)
}

// Delete mocks base method.
func (m *MockInfaqTypeRepository) Delete(id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockInfaqTypeRepositoryMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockInfaqTypeRepository)(nil).Delete), id)
}

// GetAll mocks base method.
func (m *MockInfaqTypeRepository) GetAll() ([]domain.InfaqType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].([]domain.InfaqType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockInfaqTypeRepositoryMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockInfaqTypeRepository)(nil).GetAll))
}

// GetByID mocks base method.
func (m *MockInfaqTypeRepository) GetByID(id uint) (*domain.InfaqType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*domain.InfaqType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockInfaqTypeRepositoryMockRecorder) GetByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockInfaqTypeRepository)(nil).GetByID), id)
}

// Update mocks base method.
func (m *MockInfaqTypeRepository) Update(id uint, name, description string, isActive bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", id, name, description, isActive)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockInfaqTypeRepositoryMockRecorder) Update(id, name, description, isActive any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockInfaqTypeRepository)(nil).Update), id, name, description, isActive)
}
