// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/invoice_signature_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/invoice_signature_repository.go -destination=internal/repository/mocks/mock_invoice_signature_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "ppi-100-sis/internal/domain"
	repository "ppi-100-sis/internal/repository"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockInvoiceSignatureRepository is a mock of InvoiceSignatureRepository interface.
type MockInvoiceSignatureRepository struct {
	ctrl     *gomock.Controller
	recorder *MockInvoiceSignatureRepositoryMockRecorder
	isgomock struct{}
}

// MockInvoiceSignatureRepositoryMockRecorder is the mock recorder for MockInvoiceSignatureRepository.
type MockInvoiceSignatureRepositoryMockRecorder struct {
	mock *MockInvoiceSignatureRepository
}

// NewMockInvoiceSignatureRepository creates a new mock instance.
func NewMockInvoiceSignatureRepository(ctrl *gomock.Controller) *MockInvoiceSignatureRepository {
	mock := &MockInvoiceSignatureRepository{ctrl: ctrl}
	mock.recorder = &MockInvoiceSignatureRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInvoiceSignatureRepository) EXPECT() *MockInvoiceSignatureRepositoryMockRecorder {
	return m.recorder
}

// CreateSignatures mocks base method.
func (m *MockInvoiceSignatureRepository) CreateSignatures(sigs []domain.InvoiceSignature) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSignatures", sigs)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSignatures indicates an expected call of CreateSignatures.
func (mr *MockInvoiceSignatureRepositoryMockRecorder) CreateSignatures(sigs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSignatures", reflect.TypeOf((*MockInvoiceSignatureRepository)(nil).CreateSignatures), sigs)
}

// FindByShortCode mocks base method.
func (m *MockInvoiceSignatureRepository) FindByShortCode(code string) ([]domain.InvoiceSignature, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByShortCode", code)
	ret0, _ := ret[0].([]domain.InvoiceSignature)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByShortCode indicates an expected call of FindByShortCode.
func (mr *MockInvoiceSignatureRepositoryMockRecorder) FindByShortCode(code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByShortCode", reflect.TypeOf((*MockInvoiceSignatureRepository)(nil).FindByShortCode), code)
}

// FindByTypeAndRef mocks base method.
func (m *MockInvoiceSignatureRepository) FindByTypeAndRef(invoiceType, referenceID string) ([]domain.InvoiceSignature, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByTypeAndRef", invoiceType, referenceID)
	ret0, _ := ret[0].([]domain.InvoiceSignature)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByTypeAndRef indicates an expected call of FindByTypeAndRef.
func (mr *MockInvoiceSignatureRepositoryMockRecorder) FindByTypeAndRef(invoiceType, referenceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByTypeAndRef", reflect.TypeOf((*MockInvoiceSignatureRepository)(nil).FindByTypeAndRef), invoiceType, referenceID)
}

// FindByVerificationCode mocks base method.
func (m *MockInvoiceSignatureRepository) FindByVerificationCode(code string) ([]domain.InvoiceSignature, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByVerificationCode", code)
	ret0, _ := ret[0].([]domain.InvoiceSignature)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByVerificationCode indicates an expected call of FindByVerificationCode.
func (mr *MockInvoiceSignatureRepositoryMockRecorder) FindByVerificationCode(code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByVerificationCode", reflect.TypeOf((*MockInvoiceSignatureRepository)(nil).FindByVerificationCode), code)
}

// GetConfigByID mocks base method.
func (m *MockInvoiceSignatureRepository) GetConfigByID(id uint) (*domain.InvoiceNumberConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfigByID", id)
	ret0, _ := ret[0].(*domain.InvoiceNumberConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConfigByID indicates an expected call of GetConfigByID.
func (mr *MockInvoiceSignatureRepositoryMockRecorder) GetConfigByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfigByID", reflect.TypeOf((*MockInvoiceSignatureRepository)(nil).GetConfigByID), id)
}

// GetConfigByType mocks base method.
func (m *MockInvoiceSignatureRepository) GetConfigByType(invoiceType string) (*domain.InvoiceNumberConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfigByType", invoiceType)
	ret0, _ := ret[0].(*domain.InvoiceNumberConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConfigByType indicates an expected call of GetConfigByType.
func (mr *MockInvoiceSignatureRepositoryMockRecorder) GetConfigByType(invoiceType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfigByType", reflect.TypeOf((*MockInvoiceSignatureRepository)(nil).GetConfigByType), invoiceType)
}

// GetConfigs mocks base method.
func (m *MockInvoiceSignatureRepository) GetConfigs() ([]domain.InvoiceNumberConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfigs")
	ret0, _ := ret[0].([]domain.InvoiceNumberConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConfigs indicates an expected call of GetConfigs.
func (mr *MockInvoiceSignatureRepositoryMockRecorder) GetConfigs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfigs", reflect.TypeOf((*MockInvoiceSignatureRepository)(nil).GetConfigs))
}

// GetInvoiceHistory mocks base method.
func (m *MockInvoiceSignatureRepository) GetInvoiceHistory(userIDStr string, roleID int, invoiceType, search, startDate, endDate string) ([]repository.InvoiceHistoryItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInvoiceHistory", userIDStr, roleID, invoiceType, search, startDate, endDate)
	ret0, _ := ret[0].([]repository.InvoiceHistoryItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInvoiceHistory indicates an expected call of GetInvoiceHistory.
func (mr *MockInvoiceSignatureRepositoryMockRecorder) GetInvoiceHistory(userIDStr, roleID, invoiceType, search, startDate, endDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInvoiceHistory", reflect.TypeOf((*MockInvoiceSignatureRepository)(nil).GetInvoiceHistory), userIDStr, roleID, invoiceType, search, startDate, endDate)
}

// GetStakeholderByID mocks base method.
func (m *MockInvoiceSignatureRepository) GetStakeholderByID(id uint) (*domain.StakeholderConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStakeholderByID", id)
	ret0, _ := ret[0].(*domain.StakeholderConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStakeholderByID indicates an expected call of GetStakeholderByID.
func (mr *MockInvoiceSignatureRepositoryMockRecorder) GetStakeholderByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStakeholderByID", reflect.TypeOf((*MockInvoiceSignatureRepository)(nil).GetStakeholderByID), id)
}

// GetStakeholders mocks base method.
func (m *MockInvoiceSignatureRepository) GetStakeholders() ([]domain.StakeholderConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStakeholders")
	ret0, _ := ret[0].([]domain.StakeholderConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStakeholders indicates an expected call of GetStakeholders.
func (mr *MockInvoiceSignatureRepositoryMockRecorder) GetStakeholders() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStakeholders", reflect.TypeOf((*MockInvoiceSignatureRepository)(nil).GetStakeholders))
}

// SaveConfig mocks base method.
func (m *MockInvoiceSignatureRepository) SaveConfig(config *domain.InvoiceNumberConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveConfig", config)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveConfig indicates an expected call of SaveConfig.
func (mr *MockInvoiceSignatureRepositoryMockRecorder) SaveConfig(config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveConfig", reflect.TypeOf((*MockInvoiceSignatureRepository)(nil).SaveConfig), config)
}

// SaveStakeholder mocks base method.
func (m *MockInvoiceSignatureRepository) SaveStakeholder(config *domain.StakeholderConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveStakeholder", config)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveStakeholder indicates an expected call of SaveStakeholder.
func (mr *MockInvoiceSignatureRepositoryMockRecorder) SaveStakeholder(config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveStakeholder", reflect.TypeOf((*MockInvoiceSignatureRepository)(nil).SaveStakeholder), config)
}

// UpdateVerificationCode mocks base method.
func (m *MockInvoiceSignatureRepository) UpdateVerificationCode(invoiceType, referenceID, code, docDate string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateVerificationCode", invoiceType, referenceID, code, docDate)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateVerificationCode indicates an expected call of UpdateVerificationCode.
func (mr *MockInvoiceSignatureRepositoryMockRecorder) UpdateVerificationCode(invoiceType, referenceID, code, docDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateVerificationCode", reflect.TypeOf((*MockInvoiceSignatureRepository)(nil).UpdateVerificationCode), invoiceType, referenceID, code, docDate)
}
