// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/external_debt_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/external_debt_repository.go -destination=internal/repository/mocks/mock_external_debt_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "ppi-100-sis/internal/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockExternalDebtRepository is a mock of ExternalDebtRepository interface.
type MockExternalDebtRepository struct {
	ctrl     *gomock.Controller
	recorder *MockExternalDebtRepositoryMockRecorder
	isgomock struct{}
}

// MockExternalDebtRepositoryMockRecorder is the mock recorder for MockExternalDebtRepository.
type MockExternalDebtRepositoryMockRecorder struct {
	mock *MockExternalDebtRepository
}

// NewMockExternalDebtRepository creates a new mock instance.
func NewMockExternalDebtRepository(ctrl *gomock.Controller) *MockExternalDebtRepository {
	mock := &MockExternalDebtRepository{ctrl: ctrl}
	mock.recorder = &MockExternalDebtRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExternalDebtRepository) EXPECT() *MockExternalDebtRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockExternalDebtRepository) Create(debt *domain.ExternalDebt) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", debt)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockExternalDebtRepositoryMockRecorder) Create(debt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockExternalDebtRepository)(nil).Create), debt)
}

// Delete mocks base method.
func (m *MockExternalDebtRepository) Delete(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockExternalDebtRepositoryMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockExternalDebtRepository)(nil).Delete), id)
}

// GetAll mocks base method.
func (m *MockExternalDebtRepository) GetAll() ([]domain.ExternalDebt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].([]domain.ExternalDebt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockExternalDebtRepositoryMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockExternalDebtRepository)(nil).GetAll))
}

// GetByID mocks base method.
func (m *MockExternalDebtRepository) GetByID(id string) (*domain.ExternalDebt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*domain.ExternalDebt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockExternalDebtRepositoryMockRecorder) GetByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockExternalDebtRepository)(nil).GetByID), id)
}

// GetPayments mocks base method.
func (m *MockExternalDebtRepository) GetPayments(debtID string) ([]domain.ExternalDebtPayment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPayments", debtID)
	ret0, _ := ret[0].([]domain.ExternalDebtPayment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPayments indicates an expected call of GetPayments.
func (mr *MockExternalDebtRepositoryMockRecorder) GetPayments(debtID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPayments", reflect.TypeOf((*MockExternalDebtRepository)(nil).GetPayments), debtID)
}

// RecalcStatus mocks base method.
func (m *MockExternalDebtRepository) RecalcStatus(debt *domain.ExternalDebt) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecalcStatus", debt)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecalcStatus indicates an expected call of RecalcStatus.
func (mr *MockExternalDebtRepositoryMockRecorder) RecalcStatus(debt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecalcStatus", reflect.TypeOf((*MockExternalDebtRepository)(nil).RecalcStatus), debt)
}

// RecordPaymentTx mocks base method.
func (m *MockExternalDebtRepository) RecordPaymentTx(debt *domain.ExternalDebt, payment *domain.ExternalDebtPayment, fundSource string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordPaymentTx", debt, payment, fundSource)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordPaymentTx indicates an expected call of RecordPaymentTx.
func (mr *MockExternalDebtRepositoryMockRecorder) RecordPaymentTx(debt, payment, fundSource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordPaymentTx", reflect.TypeOf((*MockExternalDebtRepository)(nil).RecordPaymentTx), debt, payment, fundSource)
}

// Update mocks base method.
func (m *MockExternalDebtRepository) Update(debt *domain.ExternalDebt, updates map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", debt, updates)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockExternalDebtRepositoryMockRecorder) Update(debt, updates any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockExternalDebtRepository)(nil).Update), debt, updates)
}
