// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/finance_extended_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/finance_extended_repository.go -destination=internal/repository/mocks/mock_finance_extended_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "ppi-100-sis/internal/domain"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockFinanceExtendedRepository is a mock of FinanceExtendedRepository interface.
type MockFinanceExtendedRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFinanceExtendedRepositoryMockRecorder
	isgomock struct{}
}

// MockFinanceExtendedRepositoryMockRecorder is the mock recorder for MockFinanceExtendedRepository.
type MockFinanceExtendedRepositoryMockRecorder struct {
	mock *MockFinanceExtendedRepository
}

// NewMockFinanceExtendedRepository creates a new mock instance.
func NewMockFinanceExtendedRepository(ctrl *gomock.Controller) *MockFinanceExtendedRepository {
	mock := &MockFinanceExtendedRepository{ctrl: ctrl}
	mock.recorder = &MockFinanceExtendedRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFinanceExtendedRepository) EXPECT() *MockFinanceExtendedRepositoryMockRecorder {
	return m.recorder
}

// AddCashLedgerEntry mocks base method.
func (m *MockFinanceExtendedRepository) AddCashLedgerEntry(req *domain.CashLedger) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddCashLedgerEntry", req)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddCashLedgerEntry indicates an expected call of AddCashLedgerEntry.
func (mr *MockFinanceExtendedRepositoryMockRecorder) AddCashLedgerEntry(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCashLedgerEntry", reflect.TypeOf((*MockFinanceExtendedRepository)(nil).AddCashLedgerEntry), req)
}

// AddDailyInfaqEntry mocks base method.
func (m *MockFinanceExtendedRepository) AddDailyInfaqEntry(req *domain.DailyInfaq) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddDailyInfaqEntry", req)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddDailyInfaqEntry indicates an expected call of AddDailyInfaqEntry.
func (mr *MockFinanceExtendedRepositoryMockRecorder) AddDailyInfaqEntry(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddDailyInfaqEntry", reflect.TypeOf((*MockFinanceExtendedRepository)(nil).AddDailyInfaqEntry), req)
}

// CreateAcademicYear mocks base method.
func (m *MockFinanceExtendedRepository) CreateAcademicYear(year *domain.AcademicYear) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAcademicYear", year)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAcademicYear indicates an expected call of CreateAcademicYear.
func (mr *MockFinanceExtendedRepositoryMockRecorder) CreateAcademicYear(year any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAcademicYear", reflect.TypeOf((*MockFinanceExtendedRepository)(nil).CreateAcademicYear), year)
}

// DeleteAcademicYear mocks base method.
func (m *MockFinanceExtendedRepository) DeleteAcademicYear(id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAcademicYear", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAcademicYear indicates an expected call of DeleteAcademicYear.
func (mr *MockFinanceExtendedRepositoryMockRecorder) DeleteAcademicYear(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAcademicYear", reflect.TypeOf((*MockFinanceExtendedRepository)(nil).DeleteAcademicYear), id)
}

// DeleteCashLedgerEntry mocks base method.
func (m *MockFinanceExtendedRepository) DeleteCashLedgerEntry(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCashLedgerEntry", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCashLedgerEntry indicates an expected call of DeleteCashLedgerEntry.
func (mr *MockFinanceExtendedRepositoryMockRecorder) DeleteCashLedgerEntry(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCashLedgerEntry", reflect.TypeOf((*MockFinanceExtendedRepository)(nil).DeleteCashLedgerEntry), id)
}

// DeleteDailyInfaqEntry mocks base method.
func (m *MockFinanceExtendedRepository) DeleteDailyInfaqEntry(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDailyInfaqEntry", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDailyInfaqEntry indicates an expected call of DeleteDailyInfaqEntry.
func (mr *MockFinanceExtendedRepositoryMockRecorder) DeleteDailyInfaqEntry(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDailyInfaqEntry", reflect.TypeOf((*MockFinanceExtendedRepository)(nil).DeleteDailyInfaqEntry), id)
}

// GetAllAcademicYears mocks base method.
func (m *MockFinanceExtendedRepository) GetAllAcademicYears() ([]domain.AcademicYear, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllAcademicYears")
	ret0, _ := ret[0].([]domain.AcademicYear)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllAcademicYears indicates an expected call of GetAllAcademicYears.
func (mr *MockFinanceExtendedRepositoryMockRecorder) GetAllAcademicYears() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllAcademicYears", reflect.TypeOf((*MockFinanceExtendedRepository)(nil).GetAllAcademicYears))
}

// GetAllSavingAccounts mocks base method.
func (m *MockFinanceExtendedRepository) GetAllSavingAccounts() ([]domain.SavingAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllSavingAccounts")
	ret0, _ := ret[0].([]domain.SavingAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllSavingAccounts indicates an expected call of GetAllSavingAccounts.
func (mr *MockFinanceExtendedRepositoryMockRecorder) GetAllSavingAccounts() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllSavingAccounts", reflect.TypeOf((*MockFinanceExtendedRepository)(nil).GetAllSavingAccounts))
}

// GetCashLedger mocks base method.
func (m *MockFinanceExtendedRepository) GetCashLedger() ([]domain.CashLedger, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCashLedger")
	ret0, _ := ret[0].([]domain.CashLedger)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCashLedger indicates an expected call of GetCashLedger.
func (mr *MockFinanceExtendedRepositoryMockRecorder) GetCashLedger() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCashLedger", reflect.TypeOf((*MockFinanceExtendedRepository)(nil).GetCashLedger))
}

// GetDailyInfaq mocks base method.
func (m *MockFinanceExtendedRepository) GetDailyInfaq() ([]domain.DailyInfaq, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDailyInfaq")
	ret0, _ := ret[0].([]domain.DailyInfaq)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDailyInfaq indicates an expected call of GetDailyInfaq.
func (mr *MockFinanceExtendedRepositoryMockRecorder) GetDailyInfaq() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDailyInfaq", reflect.TypeOf((*MockFinanceExtendedRepository)(nil).GetDailyInfaq))
}

// GetDashboardAnalytics mocks base method.
func (m *MockFinanceExtendedRepository) GetDashboardAnalytics() (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDashboardAnalytics")
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDashboardAnalytics indicates an expected call of GetDashboardAnalytics.
func (mr *MockFinanceExtendedRepositoryMockRecorder) GetDashboardAnalytics() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDashboardAnalytics", reflect.TypeOf((*MockFinanceExtendedRepository)(nil).GetDashboardAnalytics))
}

// GetSavingAccountByUserID mocks base method.
func (m *MockFinanceExtendedRepository) GetSavingAccountByUserID(userID uuid.UUID) (*domain.SavingAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSavingAccountByUserID", userID)
	ret0, _ := ret[0].(*domain.SavingAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSavingAccountByUserID indicates an expected call of GetSavingAccountByUserID.
func (mr *MockFinanceExtendedRepositoryMockRecorder) GetSavingAccountByUserID(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSavingAccountByUserID", reflect.TypeOf((*MockFinanceExtendedRepository)(nil).GetSavingAccountByUserID), userID)
}

// GetSavingAccountsByParentID mocks base method.
func (m *MockFinanceExtendedRepository) GetSavingAccountsByParentID(parentID uuid.UUID) ([]domain.SavingAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSavingAccountsByParentID", parentID)
	ret0, _ := ret[0].([]domain.SavingAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSavingAccountsByParentID indicates an expected call of GetSavingAccountsByParentID.
func (mr *MockFinanceExtendedRepositoryMockRecorder) GetSavingAccountsByParentID(parentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSavingAccountsByParentID", reflect.TypeOf((*MockFinanceExtendedRepository)(nil).GetSavingAccountsByParentID), parentID)
}

// GetSavingTransactions mocks base method.
func (m *MockFinanceExtendedRepository) GetSavingTransactions(accountID uuid.UUID) ([]domain.SavingTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSavingTransactions", accountID)
	ret0, _ := ret[0].([]domain.SavingTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSavingTransactions indicates an expected call of GetSavingTransactions.
func (mr *MockFinanceExtendedRepositoryMockRecorder) GetSavingTransactions(accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSavingTransactions", reflect.TypeOf((*MockFinanceExtendedRepository)(nil).GetSavingTransactions), accountID)
}

// GetSavingsOperationalHistory mocks base method.
func (m *MockFinanceExtendedRepository) GetSavingsOperationalHistory() ([]domain.SavingsOperationalWithdrawal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSavingsOperationalHistory")
	ret0, _ := ret[0].([]domain.SavingsOperationalWithdrawal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSavingsOperationalHistory indicates an expected call of GetSavingsOperationalHistory.
func (mr *MockFinanceExtendedRepositoryMockRecorder) GetSavingsOperationalHistory() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSavingsOperationalHistory", reflect.TypeOf((*MockFinanceExtendedRepository)(nil).GetSavingsOperationalHistory))
}

// GetSavingsOperationalReturns mocks base method.
func (m *MockFinanceExtendedRepository) GetSavingsOperationalReturns(withdrawalID uuid.UUID) ([]domain.SavingsOperationalReturn, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSavingsOperationalReturns", withdrawalID)
	ret0, _ := ret[0].([]domain.SavingsOperationalReturn)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSavingsOperationalReturns indicates an expected call of GetSavingsOperationalReturns.
func (mr *MockFinanceExtendedRepositoryMockRecorder) GetSavingsOperationalReturns(withdrawalID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSavingsOperationalReturns", reflect.TypeOf((*MockFinanceExtendedRepository)(nil).GetSavingsOperationalReturns), withdrawalID)
}

// GetSavingsPoolSummary mocks base method.
func (m *MockFinanceExtendedRepository) GetSavingsPoolSummary() (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSavingsPoolSummary")
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSavingsPoolSummary indicates an expected call of GetSavingsPoolSummary.
func (mr *MockFinanceExtendedRepositoryMockRecorder) GetSavingsPoolSummary() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSavingsPoolSummary", reflect.TypeOf((*MockFinanceExtendedRepository)(nil).GetSavingsPoolSummary))
}

// GetStudentSavingAccount mocks base method.
func (m *MockFinanceExtendedRepository) GetStudentSavingAccount(studentID uuid.UUID) (*domain.SavingAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStudentSavingAccount", studentID)
	ret0, _ := ret[0].(*domain.SavingAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStudentSavingAccount indicates an expected call of GetStudentSavingAccount.
func (mr *MockFinanceExtendedRepositoryMockRecorder) GetStudentSavingAccount(studentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStudentSavingAccount", reflect.TypeOf((*MockFinanceExtendedRepository)(nil).GetStudentSavingAccount), studentID)
}

// ProcessSavingTransaction mocks base method.
func (m *MockFinanceExtendedRepository) ProcessSavingTransaction(studentID, handledByID uuid.UUID, txnType string, amount float64, notes string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessSavingTransaction", studentID, handledByID, txnType, amount, notes)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessSavingTransaction indicates an expected call of ProcessSavingTransaction.
func (mr *MockFinanceExtendedRepositoryMockRecorder) ProcessSavingTransaction(studentID, handledByID, txnType, amount, notes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessSavingTransaction", reflect.TypeOf((*MockFinanceExtendedRepository)(nil).ProcessSavingTransaction), studentID, handledByID, txnType, amount, notes)
}

// ReturnSavingsOperational mocks base method.
func (m *MockFinanceExtendedRepository) ReturnSavingsOperational(withdrawalID, handledByID uuid.UUID, amount float64, notes string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReturnSavingsOperational", withdrawalID, handledByID, amount, notes)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReturnSavingsOperational indicates an expected call of ReturnSavingsOperational.
func (mr *MockFinanceExtendedRepositoryMockRecorder) ReturnSavingsOperational(withdrawalID, handledByID, amount, notes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReturnSavingsOperational", reflect.TypeOf((*MockFinanceExtendedRepository)(nil).ReturnSavingsOperational), withdrawalID, handledByID, amount, notes)
}

// SetActiveAcademicYear mocks base method.
func (m *MockFinanceExtendedRepository) SetActiveAcademicYear(id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetActiveAcademicYear", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetActiveAcademicYear indicates an expected call of SetActiveAcademicYear.
func (mr *MockFinanceExtendedRepositoryMockRecorder) SetActiveAcademicYear(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetActiveAcademicYear", reflect.TypeOf((*MockFinanceExtendedRepository)(nil).SetActiveAcademicYear), id)
}

// TransferSavings mocks base method.
func (m *MockFinanceExtendedRepository) TransferSavings(studentID, handledByID uuid.UUID, module, direction string, amount float64, notes string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TransferSavings", studentID, handledByID, module, direction, amount, notes)
	ret0, _ := ret[0].(error)
	return ret0
}

// TransferSavings indicates an expected call of TransferSavings.
func (mr *MockFinanceExtendedRepositoryMockRecorder) TransferSavings(studentID, handledByID, module, direction, amount, notes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TransferSavings", reflect.TypeOf((*MockFinanceExtendedRepository)(nil).TransferSavings), studentID, handledByID, module, direction, amount, notes)
}

// UpdateAcademicYear mocks base method.
func (m *MockFinanceExtendedRepository) UpdateAcademicYear(year *domain.AcademicYear) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAcademicYear", year)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAcademicYear indicates an expected call of UpdateAcademicYear.
func (mr *MockFinanceExtendedRepositoryMockRecorder) UpdateAcademicYear(year any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAcademicYear", reflect.TypeOf((*MockFinanceExtendedRepository)(nil).UpdateAcademicYear), year)
}

// UpdateCashLedgerEntry mocks base method.
func (m *MockFinanceExtendedRepository) UpdateCashLedgerEntry(req *domain.CashLedger) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCashLedgerEntry", req)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCashLedgerEntry indicates an expected call of UpdateCashLedgerEntry.
func (mr *MockFinanceExtendedRepositoryMockRecorder) UpdateCashLedgerEntry(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCashLedgerEntry", reflect.TypeOf((*MockFinanceExtendedRepository)(nil).UpdateCashLedgerEntry), req)
}

// UpdateDailyInfaqEntry mocks base method.
func (m *MockFinanceExtendedRepository) UpdateDailyInfaqEntry(req *domain.DailyInfaq) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDailyInfaqEntry", req)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDailyInfaqEntry indicates an expected call of UpdateDailyInfaqEntry.
func (mr *MockFinanceExtendedRepositoryMockRecorder) UpdateDailyInfaqEntry(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDailyInfaqEntry", reflect.TypeOf((*MockFinanceExtendedRepository)(nil).UpdateDailyInfaqEntry), req)
}

// WithdrawSavingsOperational mocks base method.
func (m *MockFinanceExtendedRepository) WithdrawSavingsOperational(handledByID uuid.UUID, amount float64, purpose string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithdrawSavingsOperational", handledByID, amount, purpose)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithdrawSavingsOperational indicates an expected call of WithdrawSavingsOperational.
func (mr *MockFinanceExtendedRepositoryMockRecorder) WithdrawSavingsOperational(handledByID, amount, purpose any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithdrawSavingsOperational", reflect.TypeOf((*MockFinanceExtendedRepository)(nil).WithdrawSavingsOperational), handledByID, amount, purpose)
}
