package usecase

import (
	"testing"
	"time"

	"ppi-100-sis/internal/domain"
	"github.com/google/uuid"
)

// TestDeletePaidObligationSafetyPolicy tests the safety check and force delete toggle behavior
func TestDeletePaidObligationSafetyPolicy(t *testing.T) {
	tests := []struct {
		name                 string
		settingValue         string
		settingExists        bool
		paidAmount           float64
		expectedDeleteAllowed bool
		expectedErrMsg       string
	}{
		{
			name:                 "Default safe mode blocks deleting paid obligation",
			settingValue:         "false",
			settingExists:        true,
			paidAmount:           250000,
			expectedDeleteAllowed: false,
			expectedErrMsg:       "tidak bisa menghapus tanggungan yang sudah memiliki riwayat pembayaran",
		},
		{
			name:                 "Missing setting defaults to blocking paid deletion",
			settingValue:         "",
			settingExists:        false,
			paidAmount:           500000,
			expectedDeleteAllowed: false,
			expectedErrMsg:       "tidak bisa menghapus tanggungan yang sudah memiliki riwayat pembayaran",
		},
		{
			name:                 "Unpaid obligation can always be deleted even when setting is false",
			settingValue:         "false",
			settingExists:        true,
			paidAmount:           0,
			expectedDeleteAllowed: true,
			expectedErrMsg:       "",
		},
		{
			name:                 "Correction mode enabled allows deleting paid obligation",
			settingValue:         "true",
			settingExists:        true,
			paidAmount:           350000,
			expectedDeleteAllowed: true,
			expectedErrMsg:       "",
		},
		{
			name:                 "Correction mode enabled allows deleting partially paid obligation",
			settingValue:         "true",
			settingExists:        true,
			paidAmount:           100000,
			expectedDeleteAllowed: true,
			expectedErrMsg:       "",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			// Simulate the check performed in StudentObligationUsecase.Delete
			isAllowed := tt.settingExists && tt.settingValue == "true"
			var err error
			if tt.paidAmount > 0 && !isAllowed {
				err = domain.ErrExistingPayment
			}

			if tt.expectedDeleteAllowed && err != nil {
				t.Fatalf("Expected deletion to be allowed, but got error: %v", err)
			}

			if !tt.expectedDeleteAllowed && err == nil {
				t.Fatalf("Expected deletion to be blocked for paid obligation, but it was allowed")
			}
		})
	}
}

// TestCashLedgerObligationIDBinding ensures CashLedger models properly associate with ObligationID
func TestCashLedgerObligationIDBinding(t *testing.T) {
	obID := uuid.New()
	ledger := domain.CashLedger{
		Source:            "Pembayaran Tanggungan Siswa",
		ItemName:          "SPP Bulanan - Juli",
		Type:              "Income",
		Amount:            250000,
		AutoGenerated:     true,
		ObligationID:      &obID,
	}

	if ledger.ObligationID == nil || *ledger.ObligationID != obID {
		t.Fatalf("Expected CashLedger.ObligationID to equal %v, got %v", obID, ledger.ObligationID)
	}
}

// TestRKASRealizationDecrementation tests the mathematical invariant of realisasi reduction
func TestRKASRealizationDecrementation(t *testing.T) {
	initialRealized := 1500000.0
	paymentToDelete := 350000.0

	// Simulating GREATEST(0, realized_amount - amount)
	updatedRealized := initialRealized - paymentToDelete
	if updatedRealized < 0 {
		updatedRealized = 0
	}

	expected := 1150000.0
	if updatedRealized != expected {
		t.Fatalf("Expected realized amount to be %f, got %f", expected, updatedRealized)
	}

	// Test boundary case: deleting payment greater than recorded realization (should not become negative)
	oversizedPayment := 2000000.0
	clampedRealized := initialRealized - oversizedPayment
	if clampedRealized < 0 {
		clampedRealized = 0
	}

	if clampedRealized != 0 {
		t.Fatalf("Expected clamped realization to be 0, got %f", clampedRealized)
	}
}

// TestPaymentTypeDeleteSafetyPolicy tests the safety check when deleting a payment type with paid obligations
func TestPaymentTypeDeleteSafetyPolicy(t *testing.T) {
	type obligationItem struct {
		id         uuid.UUID
		paidAmount float64
	}

	tests := []struct {
		name         string
		settingValue string
		obligations  []obligationItem
		expectError  bool
	}{
		{
			name:         "Payment type with paid obligations cannot be deleted in safe mode",
			settingValue: "false",
			obligations: []obligationItem{
				{id: uuid.New(), paidAmount: 0},
				{id: uuid.New(), paidAmount: 500000},
			},
			expectError: true,
		},
		{
			name:         "Payment type with only unpaid obligations can be deleted",
			settingValue: "false",
			obligations: []obligationItem{
				{id: uuid.New(), paidAmount: 0},
				{id: uuid.New(), paidAmount: 0},
			},
			expectError: false,
		},
		{
			name:         "Payment type with paid obligations can be deleted in correction mode",
			settingValue: "true",
			obligations: []obligationItem{
				{id: uuid.New(), paidAmount: 250000},
			},
			expectError: false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			hasPaid := false
			for _, ob := range tt.obligations {
				if ob.paidAmount > 0 {
					hasPaid = true
					break
				}
			}

			allowed := tt.settingValue == "true"
			var err error
			if hasPaid && !allowed {
				err = domain.ErrExistingPayment
			}

			if tt.expectError && err == nil {
				t.Fatalf("Expected error when deleting payment type with paid obligations, got nil")
			}
			if !tt.expectError && err != nil {
				t.Fatalf("Expected no error, got: %v", err)
			}
		})
	}
}

// TestUpdateSavingTransactionDate tests updating a saving transaction's date
func TestUpdateSavingTransactionDate(t *testing.T) {
	originalDate := time.Date(2026, time.August, 15, 10, 30, 0, 0, time.UTC)
	newDate := time.Date(2026, time.August, 10, 8, 0, 0, 0, time.UTC)

	txn := domain.SavingTransaction{
		ID:        uuid.New(),
		AccountID: uuid.New(),
		Type:      "Deposit",
		Amount:    100000,
		Date:      originalDate,
		Notes:     "Setoran awal",
	}

	// Test map updates with custom date
	updates := map[string]interface{}{
		"amount": 150000.0,
		"notes":  "Setoran dikoreksi",
	}
	dateSlice := []time.Time{newDate}
	if len(dateSlice) > 0 && !dateSlice[0].IsZero() {
		updates["date"] = dateSlice[0]
	}

	if updates["date"] != newDate {
		t.Fatalf("Expected date in updates map to be %v, got %v", newDate, updates["date"])
	}
	if updates["date"] == txn.Date {
		t.Fatalf("Expected updated date to differ from original txn date")
	}

	// Test date parsing logic (as handled in handler)
	dateString := "2026-08-10"
	parsed, err := time.Parse("2006-01-02", dateString)
	if err != nil {
		t.Fatalf("Failed to parse date: %v", err)
	}

	if parsed.Year() != 2026 || parsed.Month() != 8 || parsed.Day() != 10 {
		t.Fatalf("Parsed date values do not match expected: %v", parsed)
	}
}

